### ISSUE TITLE
main error

### ISSUE THREAD

**Issue by XosintCommunity** [RuskovC/GoSec-C2#1]
i dont understand how i can setup the c2 i follow all instruction and he doesnt work its normal ?

**Comment by RuskovC** [comment]
Hi, what did you dont understand ?

**Comment by RuskovC** [comment]
> i dont understand how i can setup the c2 i follow all instruction and he doesnt work its normal ?

If you have some errors take a screen and send it !

**Comment by XosintCommunity** [comment]
can i vocal with you plz

**Comment by XosintCommunity** [comment]
i dont have account for mongo db can i dont use mongo db or im obligate to use mongo db

**Comment by RuskovC** [comment]
> i dont have account for mongo db can i dont use mongo db or im obligate to use mongo db

You need to use mongodb sorry bro

**Comment by RuskovC** [comment]
> can i vocal with you plz

You can add me on Discord if you want : ruskovc

**Comment by XosintCommunity** [comment]
but its not free 
how i can use that

**Comment by RuskovC** [comment]
> but its not free how i can use that

It is... You can use free cluster
